root: true

extends:
  - "@samuelmeuli/eslint-config/react-typescript"
  - "prettier"
  - "prettier/@typescript-eslint"

env:
  browser: true
  node: true

plugins:
  - html

settings:
  import/core-modules:
    - electron

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "webpack.*.js"

  # TODO Remove rule exceptions once fixed
  "@typescript-eslint/no-var-requires": off # Seems to be broken (also marks normal imports)
  "import/named": off # Seems to be broken for TypeScript (incorrect "not found" errors)
