root: true

extends:
  - "@samuelmeuli/eslint-config/react-typescript"
  - "prettier"
  - "prettier/@typescript-eslint"

env:
  browser: true
  node: true
  jest: true

settings:
  import/core-modules:
    - electron

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "tests/**/*"
        - "webpack.*.js"
