root: true

extends:
  - "@samuelmeuli/eslint-config/react-typescript"
  - "prettier"
  - "prettier/@typescript-eslint"

env:
  browser: true
  node: true

plugins:
  - html

settings:
  import/core-modules:
    - electron

rules:
  # The usage check for devDependencies is disabled because dependencies of the renderer process
  # are declared as devDependencies so they are not bundled in the final app by electron-builder
  "import/no-extraneous-dependencies": off

  "import/named": off # TODO Currently seems to be broken for TypeScript (false positives)
