root: true

extends:
  - airbnb
  - "@samuelmeuli/eslint-config/react"
  - prettier

env:
  browser: true
  node: true

plugins:
  - html

settings:
  # Electron
  import/core-modules:
    - electron
