root: true

extends: airbnb

env:
  browser: true
  node: true

rules:
  # General rules
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  comma-dangle:
    - error
    - never
  indent:
    - error
    - tab
    - SwitchCase: 1
  no-console:
    - error
    - allow:
        - error
  no-tabs: off
  object-curly-newline: off
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false

  # React rules
  react/button-has-type: error
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
  react/jsx-indent:
    - error
    - tab
  react/jsx-indent-props:
    - error
    - tab
  react/jsx-one-expression-per-line: off

  # Project-specific rules
  import/prefer-default-export: off
  jsx-a11y/no-autofocus: off
